### ISSUE TITLE
不知道为啥，给你合不了代码了

### ISSUE THREAD

**Issue by WangShanpeng** [sienaiwun/Beihang-auto-net-login-python-script#3]
我当前的分支显示这个
> This branch is 22 commits ahead, 11 commits behind sienaiwun:master.

提交PR的时候显示这个
> There isn’t anything to compare.
> sienaiwun:master and WangShanpeng:master are entirely different commit histories.

**Comment by sienaiwun** [comment]
可能是我git rebase修改了历史commit。
试试push -f?

**Comment by WangShanpeng** [comment]
我能给我自己仓库push，我在网页上向你发起pull request的时候，就提示这两个分支完全不一样，合不了。要不你fetch一下我的仓库，再push一下试试？

**Comment by sienaiwun** [comment]
我隔些日子再试。
ps：手机端登录北航校园网有点恼人，宿舍，实验室不停切换不停登录。你有啥解决方案没？

**Comment by WangShanpeng** [comment]
> 手机端登录北航校园网有点恼人，宿舍，实验室不停切换不停登录。

啥意思，会互相顶吗？
我QQ号是402729518，有时间多交流交流。
